---
sign_in: 
sign_up: 
agent_panel: 
admin_panel: 
register: 
details: 
view_all: 
order_by: 
none: 
terms_and_conditions: 
reg_success_message: 
recover: 
oops: 
address: 
all: 
contact_us: 
confirmation: 
tags: 
login: 
post_not_found: 
view_more: 
image: 
create: 
send: 
contact_subject: 
password: 
confirm_password: 
all_posts: 
no_posts: 
title: 
description: 
status: 
actions: 
type: 
type_something: 
content: 
category: 
all_categories: 
edit_category: 
new_category: 
edit: 
delete: 
name: 
save: 
no_parent: 
add_another: 
export_to_file: 
options: 
all_pages: 
no_pages: 
manage_menu: 
menu_title: 
menu_alias: 
show_in_menu: 
page_layout: 
content_from: 
url: 
seo_options: 
meta_description: 
key_words: 
crawl_after: 
all_plugins: 
no_plugins: 
name_and_version: 
change_password: 
current_password: 
new_password: 
retype_password: 
password_reset_info_msg: 
edit_profile: 
profile_picture: 
username: 
email: 
first_name: 
last_name: 
gender: 
phone: 
about_me: 
facebook_account: 
twitter_account: 
linkedin_account: 
gp_account: 
account_msg: 
contact_email: 
webadmin_name: 
webadmin_email: 
update: 
upload: 
site_title: 
footer_text: 
site_logo: 
site_language: 
site_text_direction: 
per_page: 
default_page_layout: 
smtp_email: 
smtp_host: 
smtp_port: 
smtp_timeout: 
smtp_user: 
smtp_password: 
generate_site_map: 
sitemap_info_msg: 
pages: 
view_xml: 
create_xml: 
manage_backups: 
create_sql_backup: 
create_image_backup: 
restore: 
download: 
dashboard: 
overview_stats_more: 
visit_site: 
themes: 
locations: 
profile: 
agents: 
widgets: 
all_widgets: 
widget_positions: 
new_post: 
pages_and_menu: 
new_page: 
menu: 
system: 
edit_email_text: 
admin_settings: 
sitemap: 
activate: 
active_theme: 
available_themes: 
all_users: 
create_user: 
export_user_email: 
profile_info: 
edit_page: 
create_widget: 
widget_name: 
activate_deactivate: 
show: 
available_widgets: 
active_widgets: 
delete_warning: 
yes: 
no: 
fa_icon: 
post_ad: 
post_ad_subtitle: 
signin: 
signup: 
signup_title: 
not_found: 
purpose: 
select_category: 
upload_later_msg: 
user_panel: 
logout: 
put_as_comma_seperated: 
added: 
location: 
views: 
add_new: 
search: 
contact_mode: 
reset: 
contact: 
type_your_message: 
mail_sent: 
home: 
list_your_ad: 
print: 
remember_me: 
forgot_password: 
login_to_your_account: 
register_your_account: 
male: 
female: 
state: 
users: 
ads: 
categories: 
top_posts: 
default_site_settings: 
webadmin_settings: 
banner_settings: 
logged_in_as: 
password_change_success: 
email_sent_inbox: 
password_recovery_link_invalid: 
user_updated: 
user_deleted: 
data_inserted: 
data_updated: 
page_updated: 
page_created: 
page_deleted: 
menu_updated: 
site_map_generation_success: 
select_option: 
image_backup_created: 
language_translated: 
backup_deleted: 
database_restored: 
theme_activated: 
user_created: 
widget_position_updated: 
widget_created: 
settings_updated: 
widget_data_updated: 
unable_to_write_widget: 
admin_change_pass_help: 
login_with_google: 
login_with_facebook: 
register_for_new_account: 
site_map: 
show_site_map: 
about: 
see_full_documentation: 
admin: 
re_password: 
explain_widget_position: 
new_ad: 
select_one: 
username_or_email: 
post_detail: 
edit_user: 
the_field_is_required: 
valid_email: 
min_length: 
numeric: 
matches: 
greater_than: 
must_accept_terms: 
dont_have_permission: 
email_allready_in_use: 
username_allready_in_use: 
current_password_not_matched: 
email_not_matched: 
account_not_confirmed: 
unique_alias: 
smtp_email_settings: 
error_occured: 
user_profile: 
user_email: 
target_lang_name: 
enable_signup: 
facebook_app_settings: 
enable_facebook_login: 
fb_app_id: 
fb_secret_key: 
comment_settings: 
enable_comment: 
disqus_shortname: 
active_widget_position: 
upload_and_install: 
install_updates: 
click_and_edit: 
google_analytics_settings: 
default_seo_settings: 
find_us_on_facebook: 
type_anything: 
login_failed: 
debug_email: 
email_to: 
ive_read_the: 
title_city_category: 
css_compression: 
all_sub_categories: 
no_sub_categories: 
email_cleared: 
hide_users_profile_phone: 
features: 
new_source: 
all_sources: 
addsource: 
seo_keywords: 
seo_description: 
all_videos: 
new_video: 
create_video: 
edit_video: 
no_source: 
no_category: 
sub_category: 
category_2: 
video_updated: 
video_added: 
source: 
link: 
media: 
put_as_comma_separated: 
site_settings: 
clear_old_videos: 
videos_before: 
leave_empty_if_doesnot_matter: 
view_less_than: 
without_image: 
you_cant_undo_this_action: 
video_deleted: 
general: 
moderator: 
genaral_user_can_create_post: 
moderator_can_create_post: 
auto_crawl: 
lazy_load_images: 
generate_widgets: 
sidebar: 
pagebody: 
widget_generated: 
widget_generation_failed: 
latest_videos: 
video_by: 
top_videos: 
source_added: 
no_videos_found: 
clear: 
seen_by: 
read_this_on: 
video_source: 
video_category: 
source_name: 
parent_category: 
videos_grabbed: 
rss_url: 
auto_grabbing: 
start_on: 
grab_duration: 
item_per_grab: 
edit_source: 
source_updated: 
video_featured: 
video_un_featured: 
no_videos: 
featured_videos: 
widget_updated: 
delete_selected: 
popular_videos: 
search_result_for: 
source_type: 
make_featured: 
enable_cookie_policy_popup: 
cookie_policy_page_url: 
cookie_policy: 
cookie_policy_alert: 
read_more: 
i_agree: 
confirmation_email: 
recovery_email: 
payment_confirmation_email: 
tracking_code: 
video: 
auto_translate: 
auto_translator: 
from_lang: 
edit_email_template: 
web_email_settings: 
on: 
video_sources: 
save_images_locally: 
media_url_update: 
old_base_url: 
new_base_url: 
enable_cache: 
grabnow: 
sample_page: 
disable_main_site_link: 
admin_language: 
five_filters_api_url: 
january: 
february: 
march: 
april: 
may: 
june: 
july: 
august: 
september: 
october: 
november: 
december: 
generaluser_can_create_post: 
publish_posts_directly: 
pending_msg: 
publish: 
unpublish: 
post_approved: 
post_drafted: 
pending: 
published: 
logo_text: 
logo_text_color: 
logo_type: 
show_source_menu: 
show_cat_menu: 
enable_adblocker_alert: 
adblock_detected: 
adblock_msg: 
enable_featured_video_carousel: 
top_videos_instead_featured: 
related_videos: 
remove_featured: 
menu_type: 
youtube_app_settings: 
yt_api_key: 
youtube_channel: 
youtube_user: 
youtube_playlist: 
youtube_search: 
grab_info: 
link_or_id: 
type_link_or_id: 
loading: 
any_category: 
use_name_as_frontend_widget_title: 
channel_id_or_url: 
put_youtube_channel_id_or_url: 
search_text: 
put_youtube_search_text: 
playlist_id_or_url: 
put_youtube_playlist_id_or_url: 
user_id_or_url: 
put_youtube_user_id_or_url: 
url_not_valid: 
video_id_not_valid: 
with_video: 
autoplay_video: 
url_or_id_required: 
any_source: 
any_subcategory: 
use_youtube_publish_time: 
widget_type: 
how_to_yt_api_key: 
define_api_key_msg: 
source_deleted: 
only_published: 
only_pending: 
only_featured: 
categories_deleted: 
can_not_undo: 
how_to_get_gplus_api: 
auth_redirect_url: 
gplus_app_settings: 
enable_gplus_login: 
gplus_client_id: 
gplus_client_secret: 
